import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Space tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/space.png" />
      </Head>

      <main>
        <h1>teste</h1>
      </main>

      
    </div>
  )
}

export default Home
